name: Deploy to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git clone https://user:${HF_TOKEN}@huggingface.co/spaces/vinamra26/wikipedia-rag-chatbot space

          rsync -av \
            --exclude ".git" \
            --exclude ".github" \
            --exclude ".venv" \
            --exclude "frontend/node_modules" \
            --exclude "space" \
            ./ space/

          cd space

          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"

          git add .
          git commit -m "Auto deploy" || true
          git push